language: node_js
node_js:
- '10'
cache: yarn
script: bash scripts/build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_8d4c9ef1c494_key -iv $encrypted_8d4c9ef1c494_iv
  -in .env.production.enc -out .env.production -d
