language: node_js
node_js:
- '10'
cache: yarn
script: bash scripts/build.sh
before_install:
- echo $secret_decrypt_key | gpg --passphrase-fd 0 .env.production.gpg
env:
  global:
    secure: "mF7pfUMxQA8lZETe4BrMbHvoL+y9HrgTJJjAgCQiO6gEKymxVt+wA49DInO3iFEQ+XlcYr30hyp10Bhd9R1zcmhb5BWthcFdyF8K5cecn4DLW1wVFE++Rgn+vSfJDNPoNC2RFpYy5Iz+7yojp4zlLbN6oPn5MMmIvvGELfXOAfsDz4sfufb1ybqoG7ZnueL3p099OQATKLazP6JxR2m2UyGZHZ1epURAIOPtELZko1vZTqfpvAshZqteHnEVq0rF59KhLeiGfXhr05EjwZGsX7npPkeCmdo/VUWUpi3XMaJr9FvlIW09jWFWvaf0F5sJuSk9fa4yQy4p62PR3FKl2FymFXKaQqRlZF0LBY56WMTBf/A/TfHcazXG28G4e4m2K6eRMfErq/G7SezXXMQWmQX52asyYIBvSulfW8M+HY/DB0KD6i+Wwd3otvDHSRt9RRNdOK27F+TBogtsVIbS7XSEfHVU8qmPTojmoFOg9GVTrP6jCExwZly+ok5wVg+UBU45xUgTPsi4aUvV8WQwrv1y7TcWkQSizsjj0N81xXJmyLusxFra9oPdMcg4tmzV3YLGC0uShzunpBv5S/kyV6RFpWDqrKhH2qmlAH6qmqQGgcETnj2LCaebRgqofrpys2jsvh6KyHfLek8F1F3giQ9afUJrHmI7RnLpL4BhVRM="
